apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syfo-oppfolgingsplan-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
      autoLoginIgnorePaths:
        - /syk/oppfolgingsplan/api/isAlive
        - /syk/oppfolgingsplan/api/isReady
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  liveness:
    path: syk/oppfolgingsplan/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/oppfolgingsplan/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - 'https://www.ekstern.dev.nav.no/syk/oppfolgingsplan'
  env:
    - name: FLEXJAR_HOST
      value: "http://flexjar-backend.flex"
    - name: FLEXJAR_BACKEND_CLIENT_ID
      value: dev-gcp:flex:flexjar-backend
    - name: DINESYKMELDTE_BACKEND_HOST
      value: http://dinesykmeldte-backend
    - name: DINESYKMELDTE_BACKEND_CLIENT_ID
      value: "dev-gcp:team-esyfo:dinesykmeldte-backend"
    - name: SYFO_OPPFOLGINGSPLAN_BACKEND_HOST
      value: http://syfo-oppfolgingsplan-backend
    - name: SYFO_OPPFOLGINGSPLAN_BACKEND_CLIENT_ID
      value: "dev-gcp:team-esyfo:syfo-oppfolgingsplan-backend"
  accessPolicy:
    outbound:
      rules:
        - application: syfo-oppfolgingsplan-backend
        - application: dinesykmeldte-backend
        - application: nav-dekoratoren
          namespace: personbruker
